services:
  backend:
    image: ${DOCKER_USERNAME}/m324_backend:latest
    container_name: todo_backend
    ports:
      - "8080:8080"
    networks:
      - todo_network

  frontend:
    image: ${DOCKER_USERNAME}/m324_frontend:latest
    container_name: todo_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - todo_network

networks:
  todo_network:
    driver: bridge
