services:
  backend:
    image: ${DOCKER_USERNAME}/m324_backend:1.0
    container_name: m324_backend
    ports:
      - "8080:8080"
    networks:
      - todo_network

  frontend:
    image: ${DOCKER_USERNAME}/m324_frontend:1.0
    container_name: m324_frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - todo_network

networks:
  todo_network:
    driver: bridge
